// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: content.proto

package zusux_book_service_content

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Content service

func NewContentEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Content service

type ContentService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Content_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Content_PingPongService, error)
}

type contentService struct {
	c    client.Client
	name string
}

func NewContentService(name string, c client.Client) ContentService {
	return &contentService{
		c:    c,
		name: name,
	}
}

func (c *contentService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Content.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Content_StreamService, error) {
	req := c.c.NewRequest(c.name, "Content.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &contentServiceStream{stream}, nil
}

type Content_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type contentServiceStream struct {
	stream client.Stream
}

func (x *contentServiceStream) Close() error {
	return x.stream.Close()
}

func (x *contentServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *contentServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *contentServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *contentServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *contentService) PingPong(ctx context.Context, opts ...client.CallOption) (Content_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Content.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &contentServicePingPong{stream}, nil
}

type Content_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type contentServicePingPong struct {
	stream client.Stream
}

func (x *contentServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *contentServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *contentServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *contentServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *contentServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *contentServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Content service

type ContentHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Content_StreamStream) error
	PingPong(context.Context, Content_PingPongStream) error
}

func RegisterContentHandler(s server.Server, hdlr ContentHandler, opts ...server.HandlerOption) error {
	type content interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Content struct {
		content
	}
	h := &contentHandler{hdlr}
	return s.Handle(s.NewHandler(&Content{h}, opts...))
}

type contentHandler struct {
	ContentHandler
}

func (h *contentHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.ContentHandler.Call(ctx, in, out)
}

func (h *contentHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.ContentHandler.Stream(ctx, m, &contentStreamStream{stream})
}

type Content_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type contentStreamStream struct {
	stream server.Stream
}

func (x *contentStreamStream) Close() error {
	return x.stream.Close()
}

func (x *contentStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *contentStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *contentStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *contentStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *contentHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.ContentHandler.PingPong(ctx, &contentPingPongStream{stream})
}

type Content_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type contentPingPongStream struct {
	stream server.Stream
}

func (x *contentPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *contentPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *contentPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *contentPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *contentPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *contentPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
